### PR TITLE
Delete old backups

### PR DESCRIPTION
**Pull request by smccloud**
Added proper logic to delete old backups after user-supplied number of days.

### CODE REVIEW

**Comment by KoenZomers** [comment]
Thanks for your contribution @smccloud!

**Comment by smccloud** [comment]
> Thanks for your contribution @smccloud!

No problem.  I just like the idea of not keeping backups forever ;)

**Comment by jvivona** [comment]
This is great.  we currently wrap a powershell script around the backup to do this.  One thing to ponder ( and with a little guidance I might be able to figure it out) - each backup should respect the delete only for it's own backups.  For example - we backup multiple clients' pfSense devices into the same folder.   the 1st job run would delete all the old backups before we knew if the backup for a further device worked correctly.

Is there a way to know the filename (or file prefix) of the backup and only affect those files?

**Comment by KoenZomers** [comment]
@jvivona the filename will contain the name of your pfSense machine. The default file format is `config-<name of pfsense box>-yyyymmddhhMMss.xml`. I was a bit hesitant at first to accept this PR as I want to try to keep this tool lightweight. Things like you say can indeed easily be achieved with a bit of scripting around it. I want to avoid having dozens of parameters each for a specific use case causing nobody to understand anymore what to use when. If you have a working script around it currently, I would say stick to it. If it isn't broken, don't try to fix it :) An alternative would be to write the backups for each pfSense box to their own folder and you can leverage this new built in cleanup feature.

**Pull request merged**
