### PR TITLE
Netcore + OPNsense

### PR DESCRIPTION
**Pull request by mnaiman**
2.5 - released December 1, 2019 - download - 10 kb

    Added support for connecting to OPNSense
    Migration to .NET Core - builds are multiplaform (Windows, Linux, Mac) and self-contained (no need to install any framework).

### CODE REVIEW

**Comment by KoenZomers** [comment]
Nice one @mnaiman, thanks! I'll add it to my todo list to test it.

**Comment by KoenZomers** [comment]
Thanks again. Looks good. I've merged it and released it.

**Comment by mnaiman** [comment]
Thanks, if there will be upgrade or bug, I will make another PR.
Small promotion of tool https://forum.opnsense.org/index.php?topic=15342.0

**Comment by KoenZomers** [comment]
Thanks! I already had an open source tool for backing up OPNSense by the way: https://github.com/KoenZomers/opnSenseBackup

As I'm using pfSense myself and not OPNSense, not sure if it still works against the current latest OPNSense version. Nice to have both integrated in one tool now anyway.

**Pull request merged**
